
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js (choose version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'     # Change to your version (e.g., 16, 20)
          cache: 'npm'           # Enable caching for faster builds

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # # 4. Run tests
      # - name: Run tests
      #   run: npm test

      # 5. (Optional) Build project
      # - name: Build project
      #   run: npm run build

     
