name: product-catalog-ci
on:
   push:
     branches: [ "master" ]
   pull_request:
     branches: [ "master" ]

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        # 1. Checkout repo code
        - name: Checkout code
          uses: actions/checkout@v3

        # 2. Setup Node.js (choose version)
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'     # Change to your version (e.g., 16, 20)
            cache: 'npm'           # Enable caching for faster builds

        # 3. Install dependencies
        - name: Install dependencies
          run: npm install

        # # 4. Run tests
        # - name: Run tests
        #   run: npm test

        # 5. (Optional) Build project
        # - name: Build project
        #   run: npm run build
    docker:
       runs-on: ubuntu-latest

       needs: build
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Install Docker
           uses: docker/setup-buildx-action@v2
         - name: Login to Docker Hub
           uses: docker/login-action@v2
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_TOKEN }}
        - name: docker push
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/hello-node:${{ github.run_id }}

    # updatek8s:
    #     runs-on: ubuntu-latest

    #     needs: docker

    #     steps:
    #     - name: checkout code
    #       uses: actions/checkout@v4
    #       with:
    #         token: ${{ secrets.GITHUB_TOKEN }}

    #     - name: Update tag in kubernetes deployment manifest
    #       run: | 
    #            sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/node-hello:${{github.run_id}}|" kubernetes/deployment.yaml
        
    #     - name: Commit and push changes
    #       run: |
    #         git config --global user.email "abhishek@gmail.com"
    #         git config --global user.name "Abhishek Veeramalla"
    #         git add kubernetes/productcatalog/deploy.yaml
    #         git commit -m "[CI]: Update product catalog image tag"
    #         git push origin HEAD:main -f
