name: node-hello-ci

on:
  pull_request:
        branches:
        - master

jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: checkout-codes
        uses: actions/checkout@4
        
